<a href="https://colab.research.google.com/github/gabrielvrl/Machine-Learning-ECT/blob/master/LOP_of_mlp_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Artificial Neural Network
# from https://www.superdatascience.com/machine-learning/ 


# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Mais sobre pandas: https://github.com/Natalnet/GCiD/blob/master/Codes/Basic%20Module/01%20-%20Introdu%C3%A7%C3%A3o%20%C3%A0%20Leitura%20e%20Visualiza%C3%A7%C3%A3o%20de%20Dados.ipynb

In [230]:
# Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/ect-info/ml/master/dados/DataBaseLop.csv')


dataset.head( 1 )

   Unnamed: 0     ano  ...  diferentesExerSemanas89  diferentesExerSemanas1011
0           0  2017.2  ...                     15.0                        0.0

[1 rows x 72 columns]

In [231]:
dataset.describe()

       Unnamed: 0  ...  diferentesExerSemanas1011
count  447.000000  ...                 447.000000
mean   223.000000  ...                   2.863535
std    129.182042  ...                   5.681114
min      0.000000  ...                   0.000000
25%    111.500000  ...                   0.000000
50%    223.000000  ...                   1.000000
75%    334.500000  ...                   4.000000
max    446.000000  ...                  49.000000

[8 rows x 70 columns]

In [0]:
X = dataset.iloc[:,[2,7,8,32,37,50,55,60]].values
y = dataset.iloc[:, 11].values

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [235]:
print(X_test[0:6,:])

[[ 1.63653801 -0.31255396 -0.59632586 -0.84982843  0.92298074  0.70103251
  -0.13132124 -0.35927306]
 [-0.60085813 -1.02889385 -0.59632586  0.31627919  0.19012712 -0.99482622
  -0.13132124 -0.90137903]
 [ 0.71174761  1.12012581  0.84027735  0.31627919  0.92298074  0.08435661
  -0.13132124  0.72493888]
 [ 1.38793844 -0.31255396 -0.59632586  1.4823868   0.92298074  1.93438432
  -0.13132124  1.26704486]
 [-1.04833735  1.12012581  0.84027735  0.31627919  0.19012712  0.70103251
   0.82868231  0.72493888]
 [-0.10365898 -0.31255396 -0.59632586 -0.84982843 -0.54272651 -0.68648827
  -0.13132124 -0.35927306]]

In [0]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

In [0]:
# Adding the input layer and the first hidden layer
classifier.add(Dense( activation = 'relu', input_dim = 8, units = 4, kernel_initializer = 'uniform'))


# Adding the second hidden layer
classifier.add(Dense( activation = 'relu', units = 6, kernel_initializer = 'uniform' ))


# Adding the second hidden layer
classifier.add(Dense( activation = 'relu', units = 10, kernel_initializer = 'uniform' ))



# Adding the output layer
classifier.add(Dense( activation = 'sigmoid', units = 1, kernel_initializer = 'uniform'))

In [0]:

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [239]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 20, epochs = 50)

Epoch 1/50
424/424 [==============================] - 2s 4ms/step - loss: 0.6932 - acc: 0.4882
Epoch 2/50
424/424 [==============================] - 0s 96us/step - loss: 0.6931 - acc: 0.5071
Epoch 3/50
424/424 [==============================] - 0s 97us/step - loss: 0.6931 - acc: 0.5071
Epoch 4/50
424/424 [==============================] - 0s 108us/step - loss: 0.6929 - acc: 0.5071
Epoch 5/50
424/424 [==============================] - 0s 101us/step - loss: 0.6918 - acc: 0.5071
Epoch 6/50
424/424 [==============================] - 0s 92us/step - loss: 0.6879 - acc: 0.5071
Epoch 7/50
424/424 [==============================] - 0s 105us/step - loss: 0.6790 - acc: 0.5071
Epoch 8/50
424/424 [==============================] - 0s 100us/step - loss: 0.6611 - acc: 0.5071
Epoch 9/50
424/424 [==============================] - 0s 106us/step - loss: 0.6344 - acc: 0.6462
Epoch 10/50
424/424 [==============================] - 0s 95us/step - loss: 0.6008 - acc: 0.7759
Epoch 11/50
424/424 [==============================] - 0s 93us/step - loss: 0.5627 - acc: 0.8184
Epoch 12/50
424/424 [==============================] - 0s 94us/step - loss: 0.5301 - acc: 0.8255
Epoch 13/50
424/424 [==============================] - 0s 100us/step - loss: 0.5023 - acc: 0.8349
Epoch 14/50
424/424 [==============================] - 0s 114us/step - loss: 0.4776 - acc: 0.8420
Epoch 15/50
424/424 [==============================] - 0s 96us/step - loss: 0.4553 - acc: 0.8420
Epoch 16/50
424/424 [==============================] - 0s 99us/step - loss: 0.4367 - acc: 0.8420
Epoch 17/50
424/424 [==============================] - 0s 93us/step - loss: 0.4168 - acc: 0.8443
Epoch 18/50
424/424 [==============================] - 0s 96us/step - loss: 0.4022 - acc: 0.8467
Epoch 19/50
424/424 [==============================] - 0s 98us/step - loss: 0.3885 - acc: 0.8538
Epoch 20/50
424/424 [==============================] - 0s 102us/step - loss: 0.3767 - acc: 0.8561
Epoch 21/50
424/424 [==============================] - 0s 114us/step - loss: 0.3690 - acc: 0.8561
Epoch 22/50
424/424 [==============================] - 0s 105us/step - loss: 0.3627 - acc: 0.8585
Epoch 23/50
424/424 [==============================] - 0s 98us/step - loss: 0.3564 - acc: 0.8608
Epoch 24/50
424/424 [==============================] - 0s 99us/step - loss: 0.3505 - acc: 0.8608
Epoch 25/50
424/424 [==============================] - 0s 100us/step - loss: 0.3468 - acc: 0.8585
Epoch 26/50
424/424 [==============================] - 0s 99us/step - loss: 0.3432 - acc: 0.8656
Epoch 27/50
424/424 [==============================] - 0s 104us/step - loss: 0.3388 - acc: 0.8679
Epoch 28/50
424/424 [==============================] - 0s 106us/step - loss: 0.3363 - acc: 0.8679
Epoch 29/50
424/424 [==============================] - 0s 97us/step - loss: 0.3336 - acc: 0.8703
Epoch 30/50
424/424 [==============================] - 0s 96us/step - loss: 0.3296 - acc: 0.8703
Epoch 31/50
424/424 [==============================] - 0s 95us/step - loss: 0.3266 - acc: 0.8608
Epoch 32/50
424/424 [==============================] - 0s 99us/step - loss: 0.3256 - acc: 0.8632
Epoch 33/50
424/424 [==============================] - 0s 95us/step - loss: 0.3233 - acc: 0.8632
Epoch 34/50
424/424 [==============================] - 0s 103us/step - loss: 0.3204 - acc: 0.8679
Epoch 35/50
424/424 [==============================] - 0s 94us/step - loss: 0.3197 - acc: 0.8703
Epoch 36/50
424/424 [==============================] - 0s 93us/step - loss: 0.3179 - acc: 0.8679
Epoch 37/50
424/424 [==============================] - 0s 96us/step - loss: 0.3156 - acc: 0.8750
Epoch 38/50
424/424 [==============================] - 0s 99us/step - loss: 0.3131 - acc: 0.8750
Epoch 39/50
424/424 [==============================] - 0s 98us/step - loss: 0.3129 - acc: 0.8774
Epoch 40/50
424/424 [==============================] - 0s 104us/step - loss: 0.3095 - acc: 0.8726
Epoch 41/50
424/424 [==============================] - 0s 103us/step - loss: 0.3094 - acc: 0.8726
Epoch 42/50
424/424 [==============================] - 0s 102us/step - loss: 0.3075 - acc: 0.8750
Epoch 43/50
424/424 [==============================] - 0s 94us/step - loss: 0.3049 - acc: 0.8774
Epoch 44/50
424/424 [==============================] - 0s 98us/step - loss: 0.3048 - acc: 0.8750
Epoch 45/50
424/424 [==============================] - 0s 101us/step - loss: 0.3032 - acc: 0.8774
Epoch 46/50
424/424 [==============================] - 0s 123us/step - loss: 0.3028 - acc: 0.8726
Epoch 47/50
424/424 [==============================] - 0s 94us/step - loss: 0.3022 - acc: 0.8703
Epoch 48/50
424/424 [==============================] - 0s 105us/step - loss: 0.3017 - acc: 0.8821
Epoch 49/50
424/424 [==============================] - 0s 117us/step - loss: 0.2997 - acc: 0.8821
Epoch 50/50
424/424 [==============================] - 0s 100us/step - loss: 0.2988 - acc: 0.8844

In [240]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(y_pred[0:10])

y_pred = (y_pred > 0.5)
print(y_pred[0:10])

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

[[0.98269475]
 [0.13417563]
 [0.98124635]
 [0.98668087]
 [0.05490822]
 [0.643705  ]
 [0.08295825]
 [0.49524215]
 [0.97562575]
 [0.03555164]]
[[ True]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]]

In [241]:
print("Matriz de Confusão:")
print(cm)
print("Taxa de acerto:")
print((cm[0,0]+cm[1,1])/len(y_test) )
print(len(y_test))

Matriz de Confusão:
[[ 9  1]
 [ 3 10]]
Taxa de acerto:
0.8260869565217391
23